language: java
install: skip

os: linux
dist: trusty
jdk: openjdk11

services:
  - docker
  
script:
  - git clone https://github.com/SpitaleA/Selenium-CleanStructure.git
  - cd Selenium-CleanStructure
  - touch dockerfile
  - echo FROM selenium/standalone-chrome:4.5.3-20221024 >> dockerfile
  - echo USER root >> dockerfile
  - echo COPY . . >> dockerfile
  - echo RUN sudo curl -L https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -o gradle.zip >> dockerfile
  - echo RUN sudo unzip gradle.zip >> dockerfile
  - echo 'RUN sudo sed -i "s/src\/test\/resources\/driver\/chromedriver.exe/bin\/chromedriver/" src/test/java/factoryBrowser/Headless.java' >> dockerfile
  - echo "RUN sudo sed -i 's/properties.getProperty("browser")/"headless"/' src/test/java/utils/GetProperties.java" >> dockerfile
  - echo CMD sudo gradle-7.5.1/bin/gradle test >> dockerfile
  - docker build . -t app
  - docker run app
